### ISSUE TITLE
Fix Font of unused imports & variables 

### ISSUE THREAD

**Issue by getsbydev** [fisheva/Eva-Theme#23]
<img width="445" alt="Screenshot 2019-04-07 16 15 17" src="https://user-images.githubusercontent.com/36336399/55684911-ed991880-5950-11e9-9cab-23d416c3d7af.png">
On Line 6 I have an unused import, which i did not know, because i couldn't read the line.
It seems that this does have a strange font and color behavior. It is helpful, that it is using underscores to highlight it, but an additional greyed out font would be the best.

Awesome Theme though!

**Comment by fisheva** [comment]
The VSCode 1.3.3 update caused this problem, I just made a correction, please update the Eva Theme to version 0.7.6 to see if the problem is solved. If you still have questions, please let me know.

**Comment by getsbydev** [comment]
Thanks for the quick fix. Not it behaves as expected!

**Comment by fisheva** [comment]
Sorry, I can't display unused import in a uniform gray font, because their scope value is the same as the used import. I can only change the transparency of the unused import through the "editorUnnecessaryCode.opacity" API, and because there is already an underline mark, so I didn't reduce the transparency of the unused import.

**Comment by getsbydev** [comment]
No problem, the implementation with the underline mark is totally fine
