### ISSUE TITLE
false syntax highlight color in dart

### ISSUE THREAD

**Issue by fajaryanw** [fisheva/Eva-Theme#26]
Issue Type: **Bug**

I create a `.dart` file.
use Eva Light Theme.

add code like this :
``` dart
class Game {

  static int width = 10;
  static int height = 20;
  static int cellsize = 30;

  static int linesCleared;

  static List<List<int>> boardState;
  static List<int> rowState;
}
``` 
at line 9 `static List<List<int>> boardState;`.
last `>>` in blue color.
it should in purple color.

![dart](https://user-images.githubusercontent.com/6999559/63684982-72b19b00-c828-11e9-86e6-c704944e57ee.png)

**Comment by fisheva** [comment]
Thanks for your issue! But, unfortunately, the problem is that VSCode recognizes ">>" as a whole, not two ">", so their scope values are different. I can't set the colors of the two scope values to be the same to make here the same. So this bug can't be solved at the theme level. It's a bug of VSCode character recognition algorithm.

Press "Ctrl+Shift+P" (Windows) or "Cmd+Shift+P" (Mac) and select "Inspect TM Scopes" to view the scope values of all codes.
![image](https://user-images.githubusercontent.com/17448419/63861662-e052f800-c9dd-11e9-8e85-9418f482e15c.png)
![image](https://user-images.githubusercontent.com/17448419/63861028-b3521580-c9dc-11e9-87b8-4408ca18bf57.png)
Actually, both of their scope values are wrong, they are not "comparison" nor  "bitwise", they should be "brace" like "()" or "[ ]". I hope the VSCode team can fix such bugs someday.
