### ISSUE TITLE
Fix Activity Bar indicator Color

### ISSUE THREAD

**Issue by 1chriis1** [fisheva/Eva-Theme#32]
In vscode 1.40 an activity bar indicator was introduced(see the 1.40 release notes).
In Eva Light theme, the indicator is (by default??) black colored. 

That black color really blends in with the black bezels of any screen, so you can't even tell if it's there.
Is there any way you could change the color so it stands out against all screen bezels?

Also, if the activity bar in on the right, the activity bar indicator doesn't show up at all!

**Comment by fisheva** [comment]
After repeated attempts, I feel I don't need this indicator. 

Since the area shown in the red box indicates which button you have selected clearly. 
![image](https://user-images.githubusercontent.com/17448419/70529435-88569080-1b8b-11ea-8c68-193e04851024.png)
So I set the indicator the same color as the background. Please update Eva Theme to <del>0.7.9</del> the latest version.

**Comment by 1chriis1** [comment]
Great! Looks great now! Thank you very much!
