### ISSUE TITLE
console colors in Dark Theme

### ISSUE THREAD

**Issue by molinux** [fisheva/Eva-Theme#35]
Hi ! First of all, congratulations for this amazing theme.

I've just have one issue with it in my integrated terminal (Git Bash) on ReactJS terminal messages.
The related file with errors doesn´t appear properly as you can see in the image below

![image](https://user-images.githubusercontent.com/21347783/90963033-02654600-e48b-11ea-86c1-763dc4719ee2.png)

And here is another image with another color theme:

![image](https://user-images.githubusercontent.com/21347783/90963048-22950500-e48b-11ea-8904-43e00f4a3916.png)

**Comment by fisheva** [comment]
@molinux, really really very thanks to you! Your solution is very helpful! 

Course I don’t have much experience with Terminal. The color setting of Terminal has always been a black box for me. The official API document description is also very unclear. 

Your solution gave me a rough guess: I guess all "Terminal.ansiColor" API is the special line background color in Terminal, and all "Terminal.ansiBrightColor" API is texts' color in Terminal.

It has been a long time since the last update of Eva Theme. I am debugging some other APIs recently. I will add the terminal settings update in the next update. Give me a few days, it will not be too far.

**Comment by Basovs** [comment]
Where do i find terminal.ansiBlack to edit it?

**Comment by molinux** [comment]
@Basovs You can stylize the color of your theme in the settings.json file.

Here is an example:

```json
   "workbench.colorCustomizations": {
        "[Eva Dark]": {
            "terminal.ansiBlack": "#c3c3cc",
        },
    },
```

**Comment by fisheva** [comment]
@molinux Sorry to reply late, I updated Eva Theme 0.8.0 version a week ago. How do you feel?  Has the problem been sloved?

Since I guess all "Terminal.ansiBrightColor" APIs are the special line background colors in Terminal and all "Terminal.ansiColor" APIs are the texts' colors in Terminal, so I added 80% transparency to all "Terminal.ansiBrightColor".

Is there still any case where the background color covers the text and makes the text invisible?

In addition, is there a situation where the text color is particularly transparent and can not be seen clearly? If this phenomenon occurs, it means that my guess is not completely correct, indicating that "Terminal.ansiBrightColor" are not just APIs for some background colors, but also APIs for some text colors, then needs to be adjusted.

If you find these problems, please take me some screenshots. Thank you!

**Comment by Basovs** [comment]
Seems to be fixed! Cool theme! Thnx

**Comment by fisheva** [comment]
In order to avoid misleading people who look at this issue in the future, I am here to update my reply, because I found that my inference above is wrong.

New conclusion:
1. There is no uniform rule for "terminal.ansiColor" and "terminal.ansiBrightColor" as background color or text color.
2. Neither of these two kinds of API can set the color with transparency.
3. VSCode sets two default colors for each of these two kinds of API. The overlay relationship between the color set by the user and the two default colors is:
- When the user does not set: API displays the default color A;
- When the user sets a solid color without transparency, the API displays the solid color set by the user;
- When the user sets a color with transparency, the API displays the default color B.

According to the above rules, I set a different solid color for each API in version 0.9.3 and got the first round of feedback in [issue #37](https://github.com/fisheva/Eva-Theme/issues/37). I found the corresponding positions of some APIs in Terminal through the screenshots he sent me and made corresponding modifications, then reach the first more complete version of Terminal in 0.9.7.

But there are still some APIs that are not shown in [issue #37](https://github.com/fisheva/Eva-Theme/issues/37). I marked them with a red box in the picture below. If you find these colors in the Terminal and feel improper, please give me feedback.
![image](https://user-images.githubusercontent.com/17448419/93412454-c7aace00-f8cf-11ea-8d29-9a2555d4f1ff.png)
![image](https://user-images.githubusercontent.com/17448419/93412478-d1343600-f8cf-11ea-890e-455d097f759f.png)

In addition, if you find that the text color and the text background color in a place are two similar colors (such as "terminal.ansiBlue" and "terminal.ansiBrightBlue", "terminal.ansiGreen" and "terminal.ansiBrightGreen"), the text is not clear, please give me feedback too.
![image](https://user-images.githubusercontent.com/17448419/93414895-de9fef00-f8d4-11ea-8d35-6c22ba017cd8.png)
Thanks!

**Comment by fisheva** [comment]
Hello! Since of [issue 58](https://github.com/fisheva/Eva-Theme/issues/58), I made some changes to the APIs' colors of terminal in version 1.6.4. If you find that after the change, some words under terminal cannot be seen clearly or the background color is inappropriate, please let me know and provide screenshots for me to modify. Thank you!
