### ISSUE TITLE
Use different colors to distinguish classes from interfaces 

### ISSUE THREAD

**Issue by pasqualedante** [fisheva/Eva-Theme#63]
At this moment class and interface use the same color. From UX point of view, it would be better to have two different colors.
Thanks in advance.

![image](https://user-images.githubusercontent.com/813690/133428820-1c1bb26e-2797-4224-92b1-5a74841f8205.png)

**Comment by fisheva** [comment]
Hi, @pasqualedante 

Sorry for reply late. There are three reasons for this setting:

1) Vscode does not correctly distinguish between Interface and Class everywhere. For example, the scope values of Class and Interface in the following screenshot are exactly the same.
![企业微信截图_20210917104400](https://user-images.githubusercontent.com/17448419/133715984-365f66e1-a4e7-4b00-82b5-6bc624158109.png)
![企业微信截图_20210917104410](https://user-images.githubusercontent.com/17448419/133716002-49b1085a-c11b-4e02-a7a9-7ca3c3199c1b.png)

2) There is no other color available for the Interface currently. At present, other colors have their own stable meaning. Changing to other colors will also interfere with their semantics. And creating a new color is not easy. The newly created color shall meet the following requirements:
- Good looking
- High discrimination with existing colors
- Visible clearly under the current background color

3) The current colors of Class, Interface and Struct are the same. If set a separate color for the Interface, should Struct also set a color? Because of the second constraint, the semantic richness of the code is much more than the number of colors we can use. The semantics, writing methods and usage of Class, Interface and Struct are similar, so I temporarily give them the same color. Maybe I will find a better way to distinguish them in the future. 

---
Can you copy the code and context in your picture for me to test? I want to see why public class is pink. Thanks!

**Comment by pasqualedante** [comment]
```csharp
namespace Edigit.Views.Pannello2.ViewModels {
    using AutoMapper;
    using DevExpress.Data;
    using DevExpress.Mvvm;
    using DevExpress.Mvvm.DataAnnotations;
    using DevExpress.Mvvm.POCO;
    using DevExpress.Xpf.Bars;
    using DevExpress.Xpf.Grid;
    //...
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.IO;
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using System.Windows;
    using System.Windows.Media;

    [POCOViewModel]
    public class Pannello2ViewModel
        : ILicenseAware
        , ICiceroAware
        , IAppStatusbarBarManager {
//...
}
```
