### ISSUE TITLE
Lighter color for editorWhitespace.foreground in light themes

### ISSUE THREAD

**Issue by gulshan** [fisheva/Eva-Theme#65]
I am currently using the default "Show whitespaces on selection" option in vscode. I think the whitespaces are currently quite hard to distinguish on light Eva themes-
![image](https://user-images.githubusercontent.com/751732/135046877-e6e926b6-cbd0-435c-a596-d8627b1c22c2.png)

This is what it look like with `"editorWhitespace.foreground": "#DDD"`-
![image](https://user-images.githubusercontent.com/751732/135047179-f2e83557-f372-4f28-b20f-7d95c08a909d.png)

Please use a lighter color for `editorWhitespace.foreground` in light Eva themes, so that the whitespaces are easily visible in selection.

**Comment by fisheva** [comment]
After seeing your issues, I slightly improved the visibility of whiteSpace in version 1.7.6. 

Before
<img width="589" alt="WX20210928-235923@2x" src="https://user-images.githubusercontent.com/17448419/135123951-87d79747-d39a-469e-b584-586c62643b49.png">

After
<img width="592" alt="WX20210929-000116@2x" src="https://user-images.githubusercontent.com/17448419/135123952-1ffaba28-c195-4345-9c80-3864e7e01a49.png">

If you still feel that it is not clear enough (sorry!), please set it by yourself in Settings.

The reason why Whitespace color is not set very conspicuously is that I think Whitespace should not attract the user’s attention too much. When the user selects the code, the user’s main attention should still be on the selected code, instead of Whitespace.

**Comment by gulshan** [comment]
Thank you for the update.
