### ISSUE TITLE
Consider darker background in Eva Dark Bold for editor pane

### ISSUE THREAD

**Issue by rhyek** [fisheva/Eva-Theme#69]
I made a few customizations via my settings.json in vscode and you can see here what that looks like:

original:
![image](https://user-images.githubusercontent.com/702922/147684180-13e78d42-8346-43e4-ba79-abff04e83ae0.png)

custom:
![image](https://user-images.githubusercontent.com/702922/147684092-68a89da7-73d5-4762-9dca-7af355c31948.png)

I feel this makes it easier to read source code for me. These are the changes:

```json
"workbench.colorCustomizations": {
  "[Eva Dark Bold]": {
    "editor.background": "#21252B",
    "editorGutter.background": "#21252B",
    "sideBar.border": "#181A1F",
    "editor.lineHighlightBackground": "#282c34",
    "editor.wordHighlightBackground": "#ffffff10",
    "editor.wordHighlightStrongBackground": "#ffffff10",
  }
},
```

**Comment by fisheva** [comment]
Thanks for your advice. This question made me feel very pleasantly surprised. Because, among the users who raised issues, few people have such a clear understanding of the various settings and APIs of VSCode.

I tried your settings. My personal feeling is that after the editing background color is darkened, the font color contrast is higher and it appears clearer. But at the same time, the eyes are tighter. After watching for a long time, the eyes get tired faster. This may be different for everyone.

I found you set "editor.wordHighlightStrongBackground", I think your actual needs should be that the fonts in the background of this API are a bit unclear, so I slightly increased the transparency of this background color in the latest version(1.7.7). Hope you like it : )

**Comment by fisheva** [comment]
Thanks for your advice. This question made me feel very pleasantly surprised. Because, among the users who raised issues, few people have such a clear understanding of the various settings and APIs of VSCode.

I tried your settings. My personal feeling is that after the editing background color is darkened, the font color contrast is higher and it appears clearer. But at the same time, the eyes are tighter. After watching for a long time, the eyes get tired faster. This may be different for everyone.

I found you set "editor.wordHighlightStrongBackground", I think your actual needs should be that the fonts in the background of this API are a bit unclear, so I slightly increased the transparency of this background color in the latest version(1.7.7). Hope you like it : )

**Comment by rhyek** [comment]
You're right that the preference might be subjective, but I did see a couple other comments asking the same thing in the extension marketplace.

Btw, the hightlight background colors were only something I felt I needed to change *after* I changed the editor pane background. Didn't feel a need before.

**Comment by rhyek** [comment]
Btw I just wanted to say that your theme has made me think vscode is actually beautiful now after years of using it professionally.

**Comment by fisheva** [comment]
Most users are silent, and may only jump out to express their opinions when a certain modification makes them unbearable.

Modifying the background color of the editor pane is a very big change. Trust me, if I changed the editor pane, a few people will appreciate it, but more people will complain why the background color suddenly changes so much? There is still a strong complaint note in the Q&A of Eva Theme's Marketplace.

I can't make all users like all of the Eva Theme, so the simplest principle is to keep my own preferences.

Thanks! Some other themes are also very beautiful, just with different styles. For example, Nebula Theme.
![image](https://user-images.githubusercontent.com/17448419/147885317-889a86da-0e57-438d-a70a-24529b014fd2.png)
