### ISSUE TITLE
Firefox Theme

### ISSUE THREAD

**Issue by hmnd** [fisheva/Eva-Theme#74]
Hey @fisheva, just wanted to thank you for this awesome theme! Also wanted to give a link to [this Firefox theme](https://addons.mozilla.org/en-US/firefox/addon/eva-dark/) I created based on Eva Dark. Don't know if anyone else would be interested in it, but could add a link to the README if you wish :).

**Comment by fisheva** [comment]
Hi @hmnd, Very thanks for your love for Eva Theme. That's a very cool idea. It's my honor to add your link to the README. Would you like me to add your Github name and link in the text or not?
<img width="1543" alt="企业微信截图_cf98563b-42d9-4b33-b947-da3a5946b6a3" src="https://user-images.githubusercontent.com/17448419/160159614-81bb8225-55bf-4b1b-8628-3d519d3d021a.png">

**Comment by hmnd** [comment]
@fisheva Sure :) Thank you!

**Comment by fisheva** [comment]
Users can see your link in 1.7.9 Eva Theme now :D

Btw, I'd like here link to Eva Theme [marketplace](https://marketplace.visualstudio.com/items?itemName=fisheva.Eva-Theme) instead of Github repository. Thanks!
<img width="842" alt="企业微信20220326-172242@2x" src="https://user-images.githubusercontent.com/17448419/160233363-84d571fe-326b-46a0-a350-9f0855c9d2db.png">

**Comment by hmnd** [comment]
@fisheva Awesome, thank you! I've corrected the link :)
