### ISSUE TITLE
Visual Studio 2022 version and Visual Studio Code version are different

### ISSUE THREAD

**Issue by ashen92** [fisheva/Eva-Theme#76]
### Screenshot
![image](https://user-images.githubusercontent.com/59907222/171624139-061fb695-8b3b-4acd-8a71-8afa9ef14c0f.png)

## Supplement
Visual Studio 2022 theme is not same as VSCode theme. Some colours are different, some are bright

**Comment by fisheva** [comment]
Hi, this is because VSCode has a convenient code scope value viewing tool, which can accurately locate each code fragment. 
<img width="783" alt="QQ20220604-224951@2x" src="https://user-images.githubusercontent.com/17448419/172008593-2530bca0-14f2-4c64-97e0-dca72eaf0104.png">

And Visual Studio can only set the code color in fonts and colors, I am unfamiliar with programming languages other than front-end. I don't understand many settings by looking at the name. 
<img width="1156" alt="QQ20220604-230224@2x" src="https://user-images.githubusercontent.com/17448419/172010378-dc1b26a3-a863-4526-8c9f-6f268db56ad5.png">

If you know the fonts and colors settings of your commonly used programming languages, please help me correct them(subject to Eva Theme of VSCode). Thanks!
